name: scidatalib_ci

env:
  PYTHON_MAIN_VERSION: 3.6
  POETRY_VERSION: 1.1.4

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install poetry==${{ env.POETRY_VERSION }}
            poetry install

      - name: Lint
        if: ${{ matrix.python-version == env.PYTHON_MAIN_VERSION }}
        run: |
            poetry run flake8
