name: Release to TestPyPi 

env:
  POETRY_VERSION: 2.1.3

on:
  push:
    tags: ['test-v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10","3.11","3.12","3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install poetry==${{ env.POETRY_VERSION }}
            poetry install

      - name: Build Python package and Upload to TestPyPi
        shell: bash -l {0}
        if: startsWith( github.ref, 'refs/tags/test-')
        env:
          TEST_PYPI_TOKEN_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry update
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi --username "__token__" --password $TEST_PYPI_TOKEN_PASSWORD
