name: Release to TestPyPi 

env:
  POETRY_VERSION: 1.1.15

on:
  push:
    branches: 'master'
    tags: 'test-v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install poetry==${{ env.POETRY_VERSION }}
            poetry install

      - name: Build Python package and Upload to TestPyPi
        shell: bash -l {0}
        if: startsWith( github.ref, 'refs/tags/test-')
        env:
          TEST_PYPI_TOKEN_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry update
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi --username "__token__" --password $TEST_PYPI_TOKEN_PASSWORD
